### ISSUE TITLE
Clé d'API manquante dans la doc

### ISSUE THREAD

**Issue by stevecohenfr** [fuwu-yuan/gameserver-api#4]
La doc (et le wiki) n'expliquent pas comment utiliser la clé d'API. J'ai essayé avec key=<key> et token=<token>. Mais ça ne fonctionne pas. Dans le header peut être ?

**Comment by stevecohenfr** [comment]
Ok, vu dans le code, il faut ajouter le header :

`auth_key: <key>`

**Comment by julien-beguier** [comment]
Je sais pas ou tu as regardé mais je l'ai mis dans la page d'accueil du wiki. Dernier edit il y a 13 jours donc c'était bien là.
